# Generated by Django 4.2.3 on 2023-07-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('place', models.CharField(max_length=50, verbose_name='Место на складе')),
                ('size', models.CharField(max_length=30, verbose_name='Размер')),
                ('material', models.CharField(max_length=30, verbose_name='Материал')),
                ('status', models.CharField(max_length=25, verbose_name='Статус')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('last_status_change', models.DateTimeField(verbose_name='Последнее изменение статуса')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('action', models.CharField(choices=[('TAKE', 'Взял'), ('RETURN', 'Вернул')], default='TAKE', max_length=6, verbose_name='Тип операции')),
                ('date', models.DateTimeField(verbose_name='Время операции')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='store.tag'),
        ),
    ]
