# Generated by Django 4.2.3 on 2023-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(choices=[(True, 'На складе'), (False, 'В работе')], verbose_name='Статус'),
        ),
    ]
