# Generated by Django 4.2.3 on 2023-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.IntegerField(default=1, verbose_name='Доступное количество'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_total',
            field=models.IntegerField(default=1, verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='No-Image-Placeholder.svg', upload_to='store/item_images/'),
        ),
    ]
