# Generated by Django 4.2.3 on 2023-12-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='No-Image-Placeholder.svg', upload_to='store/item_images/'),
        ),
    ]
