# Generated by Django 4.2.3 on 2023-12-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_item_category_alter_item_photo'),
        ('store', '0014_item_quantity_available_item_quantity_total_and_more'),
    ]

    operations = [
    ]
