# Generated by Django 4.2.3 on 2024-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_merge_20231211_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение статуса'),
        ),
    ]
