# Generated by Django 4.2.3 on 2024-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_item_last_status_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_status_change',
            field=models.DateTimeField(verbose_name='Последнее изменение статуса'),
        ),
    ]
