# Generated by Django 4.2.3 on 2024-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='noimage.svg', upload_to='store/item_images/'),
        ),
    ]
