# Generated by Django 4.2.3 on 2024-04-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_draft_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
