# Generated by Django 4.2.3 on 2024-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_summary_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='teaser',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
