# Generated by Django 4.2.3 on 2024-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='teaser',
            field=models.CharField(default='Тизер', max_length=300, verbose_name='Тизер новости'),
        ),
    ]
