# Generated by Django 4.2.3 on 2024-04-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='teaser',
            field=models.CharField(default='Тизер', max_length=300, verbose_name='Сводка'),
        ),
    ]
