# Generated by Django 4.2.3 on 2024-04-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default='news', max_length=20, verbose_name='Тип'),
        ),
    ]
